name: Develop Deploy
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Package Install
        run: npm install

      - name: Create Config File
        run: mv ./src/assets/config.example.yml ./src/assets/config.yml

      - name: Replace Config Setting
        run: sed -i -e 's/#ここにSkywayのAPIKeyを入力してください/${{ secrets.SKYWAY_API_KEY_DEVELOP }}/g' ./src/assets/config.yml

      - name: Build Application
        run: npx ng build --prod

      - name: Publish to AWS S3 & CloudFront Cache Clear
        uses: opspresso/action-s3-sync@v0.2.3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-1'
          FROM_PATH: './dist/udonarium'
          DEST_PATH: ${{ secrets.AWS_S3_BUCKET_PATH }}
